// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocs/vehicles.proto

package packets

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VehiclesRequest struct {
	Data                 *any.Any `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VehiclesRequest) Reset()         { *m = VehiclesRequest{} }
func (m *VehiclesRequest) String() string { return proto.CompactTextString(m) }
func (*VehiclesRequest) ProtoMessage()    {}
func (*VehiclesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc555a25529e21c8, []int{0}
}

func (m *VehiclesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VehiclesRequest.Unmarshal(m, b)
}
func (m *VehiclesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VehiclesRequest.Marshal(b, m, deterministic)
}
func (m *VehiclesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VehiclesRequest.Merge(m, src)
}
func (m *VehiclesRequest) XXX_Size() int {
	return xxx_messageInfo_VehiclesRequest.Size(m)
}
func (m *VehiclesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VehiclesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VehiclesRequest proto.InternalMessageInfo

func (m *VehiclesRequest) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateVehiclesRequest struct {
	VehiclesID           string   `protobuf:"bytes,1,opt,name=VehiclesID,proto3" json:"VehiclesID,omitempty"`
	Data                 *any.Any `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateVehiclesRequest) Reset()         { *m = UpdateVehiclesRequest{} }
func (m *UpdateVehiclesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateVehiclesRequest) ProtoMessage()    {}
func (*UpdateVehiclesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc555a25529e21c8, []int{1}
}

func (m *UpdateVehiclesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateVehiclesRequest.Unmarshal(m, b)
}
func (m *UpdateVehiclesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateVehiclesRequest.Marshal(b, m, deterministic)
}
func (m *UpdateVehiclesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateVehiclesRequest.Merge(m, src)
}
func (m *UpdateVehiclesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateVehiclesRequest.Size(m)
}
func (m *UpdateVehiclesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateVehiclesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateVehiclesRequest proto.InternalMessageInfo

func (m *UpdateVehiclesRequest) GetVehiclesID() string {
	if m != nil {
		return m.VehiclesID
	}
	return ""
}

func (m *UpdateVehiclesRequest) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type VehiclesRequestByID struct {
	VehiclesID           string   `protobuf:"bytes,1,opt,name=VehiclesID,proto3" json:"VehiclesID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VehiclesRequestByID) Reset()         { *m = VehiclesRequestByID{} }
func (m *VehiclesRequestByID) String() string { return proto.CompactTextString(m) }
func (*VehiclesRequestByID) ProtoMessage()    {}
func (*VehiclesRequestByID) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc555a25529e21c8, []int{2}
}

func (m *VehiclesRequestByID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VehiclesRequestByID.Unmarshal(m, b)
}
func (m *VehiclesRequestByID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VehiclesRequestByID.Marshal(b, m, deterministic)
}
func (m *VehiclesRequestByID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VehiclesRequestByID.Merge(m, src)
}
func (m *VehiclesRequestByID) XXX_Size() int {
	return xxx_messageInfo_VehiclesRequestByID.Size(m)
}
func (m *VehiclesRequestByID) XXX_DiscardUnknown() {
	xxx_messageInfo_VehiclesRequestByID.DiscardUnknown(m)
}

var xxx_messageInfo_VehiclesRequestByID proto.InternalMessageInfo

func (m *VehiclesRequestByID) GetVehiclesID() string {
	if m != nil {
		return m.VehiclesID
	}
	return ""
}

type OutputVehicles struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Data                 *any.Any `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutputVehicles) Reset()         { *m = OutputVehicles{} }
func (m *OutputVehicles) String() string { return proto.CompactTextString(m) }
func (*OutputVehicles) ProtoMessage()    {}
func (*OutputVehicles) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc555a25529e21c8, []int{3}
}

func (m *OutputVehicles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputVehicles.Unmarshal(m, b)
}
func (m *OutputVehicles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputVehicles.Marshal(b, m, deterministic)
}
func (m *OutputVehicles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputVehicles.Merge(m, src)
}
func (m *OutputVehicles) XXX_Size() int {
	return xxx_messageInfo_OutputVehicles.Size(m)
}
func (m *OutputVehicles) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputVehicles.DiscardUnknown(m)
}

var xxx_messageInfo_OutputVehicles proto.InternalMessageInfo

func (m *OutputVehicles) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *OutputVehicles) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*VehiclesRequest)(nil), "packets.VehiclesRequest")
	proto.RegisterType((*UpdateVehiclesRequest)(nil), "packets.UpdateVehiclesRequest")
	proto.RegisterType((*VehiclesRequestByID)(nil), "packets.VehiclesRequestByID")
	proto.RegisterType((*OutputVehicles)(nil), "packets.OutputVehicles")
}

func init() { proto.RegisterFile("protocs/vehicles.proto", fileDescriptor_cc555a25529e21c8) }

var fileDescriptor_cc555a25529e21c8 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2e, 0xd6, 0x2f, 0x4b, 0xcd, 0xc8, 0x4c, 0xce, 0x49, 0x2d, 0xd6, 0x03, 0x0b, 0x08,
	0xb1, 0x17, 0x24, 0x26, 0x67, 0xa7, 0x96, 0x14, 0x4b, 0x49, 0xa6, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4,
	0xea, 0x83, 0x85, 0x93, 0x4a, 0xd3, 0xf4, 0x13, 0xf3, 0x2a, 0x21, 0x6a, 0x94, 0xac, 0xb9, 0xf8,
	0xc3, 0xa0, 0xba, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x34, 0xb8, 0x58, 0x5c, 0x12,
	0x4b, 0x12, 0x25, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0x44, 0xf4, 0x20, 0x9a, 0xf5, 0x60, 0x9a,
	0xf5, 0x1c, 0xf3, 0x2a, 0x83, 0xc0, 0x2a, 0x94, 0x12, 0xb9, 0x44, 0x43, 0x0b, 0x52, 0x12, 0x4b,
	0x52, 0xd1, 0x8d, 0x90, 0xe3, 0xe2, 0x82, 0x09, 0x79, 0xba, 0x80, 0x0d, 0xe2, 0x0c, 0x42, 0x12,
	0x81, 0x5b, 0xc1, 0x44, 0xd0, 0x0a, 0x53, 0x2e, 0x61, 0x34, 0xc3, 0x9d, 0x2a, 0x3d, 0x5d, 0x08,
	0x59, 0xa0, 0x14, 0xc4, 0xc5, 0xe7, 0x5f, 0x5a, 0x52, 0x50, 0x5a, 0x02, 0x13, 0x13, 0x12, 0xe3,
	0x62, 0x0b, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x06, 0xab, 0x66, 0x0d, 0x82, 0xf2, 0x88, 0x77, 0x8a,
	0xd1, 0x7f, 0x26, 0x2e, 0x0e, 0xb8, 0x71, 0x2e, 0x5c, 0xbc, 0xce, 0x45, 0xa9, 0x08, 0xaf, 0x0b,
	0x49, 0xe8, 0x41, 0x43, 0x5b, 0x0f, 0xcd, 0xbd, 0x52, 0xe2, 0x70, 0x19, 0x54, 0x27, 0x29, 0x31,
	0x08, 0x79, 0x71, 0xf1, 0xa2, 0x04, 0xa0, 0x90, 0x1c, 0x5c, 0x2d, 0xd6, 0x80, 0xc5, 0x6f, 0x16,
	0xbf, 0x7b, 0x2a, 0x5c, 0xc0, 0xa9, 0xd2, 0x33, 0x45, 0x48, 0x06, 0x97, 0x9b, 0x40, 0x61, 0x88,
	0xcf, 0x2c, 0x5f, 0x2e, 0x21, 0x97, 0xd4, 0x9c, 0x54, 0x84, 0xfd, 0x94, 0x19, 0xe7, 0x86, 0xe2,
	0x34, 0x9f, 0xcc, 0xe2, 0x12, 0xb2, 0x82, 0xcb, 0x89, 0x3b, 0x8a, 0x53, 0xcf, 0x1a, 0x2a, 0x9b,
	0xc4, 0x06, 0x8e, 0x22, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0e, 0xf9, 0x5d, 0xec, 0xfe,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VehiclesClient is the client API for Vehicles service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VehiclesClient interface {
	CreateVehicle(ctx context.Context, in *VehiclesRequest, opts ...grpc.CallOption) (*OutputVehicles, error)
	UpdateVehicle(ctx context.Context, in *UpdateVehiclesRequest, opts ...grpc.CallOption) (*OutputVehicles, error)
	GetVehiclesById(ctx context.Context, in *VehiclesRequestByID, opts ...grpc.CallOption) (*OutputVehicles, error)
	DeleteVehiclesById(ctx context.Context, in *VehiclesRequestByID, opts ...grpc.CallOption) (*OutputVehicles, error)
	GetVehiclesList(ctx context.Context, in *VehiclesRequest, opts ...grpc.CallOption) (*OutputVehicles, error)
}

type vehiclesClient struct {
	cc *grpc.ClientConn
}

func NewVehiclesClient(cc *grpc.ClientConn) VehiclesClient {
	return &vehiclesClient{cc}
}

func (c *vehiclesClient) CreateVehicle(ctx context.Context, in *VehiclesRequest, opts ...grpc.CallOption) (*OutputVehicles, error) {
	out := new(OutputVehicles)
	err := c.cc.Invoke(ctx, "/packets.Vehicles/CreateVehicle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehiclesClient) UpdateVehicle(ctx context.Context, in *UpdateVehiclesRequest, opts ...grpc.CallOption) (*OutputVehicles, error) {
	out := new(OutputVehicles)
	err := c.cc.Invoke(ctx, "/packets.Vehicles/UpdateVehicle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehiclesClient) GetVehiclesById(ctx context.Context, in *VehiclesRequestByID, opts ...grpc.CallOption) (*OutputVehicles, error) {
	out := new(OutputVehicles)
	err := c.cc.Invoke(ctx, "/packets.Vehicles/GetVehiclesById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehiclesClient) DeleteVehiclesById(ctx context.Context, in *VehiclesRequestByID, opts ...grpc.CallOption) (*OutputVehicles, error) {
	out := new(OutputVehicles)
	err := c.cc.Invoke(ctx, "/packets.Vehicles/DeleteVehiclesById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehiclesClient) GetVehiclesList(ctx context.Context, in *VehiclesRequest, opts ...grpc.CallOption) (*OutputVehicles, error) {
	out := new(OutputVehicles)
	err := c.cc.Invoke(ctx, "/packets.Vehicles/GetVehiclesList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VehiclesServer is the server API for Vehicles service.
type VehiclesServer interface {
	CreateVehicle(context.Context, *VehiclesRequest) (*OutputVehicles, error)
	UpdateVehicle(context.Context, *UpdateVehiclesRequest) (*OutputVehicles, error)
	GetVehiclesById(context.Context, *VehiclesRequestByID) (*OutputVehicles, error)
	DeleteVehiclesById(context.Context, *VehiclesRequestByID) (*OutputVehicles, error)
	GetVehiclesList(context.Context, *VehiclesRequest) (*OutputVehicles, error)
}

// UnimplementedVehiclesServer can be embedded to have forward compatible implementations.
type UnimplementedVehiclesServer struct {
}

func (*UnimplementedVehiclesServer) CreateVehicle(ctx context.Context, req *VehiclesRequest) (*OutputVehicles, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVehicle not implemented")
}
func (*UnimplementedVehiclesServer) UpdateVehicle(ctx context.Context, req *UpdateVehiclesRequest) (*OutputVehicles, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVehicle not implemented")
}
func (*UnimplementedVehiclesServer) GetVehiclesById(ctx context.Context, req *VehiclesRequestByID) (*OutputVehicles, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVehiclesById not implemented")
}
func (*UnimplementedVehiclesServer) DeleteVehiclesById(ctx context.Context, req *VehiclesRequestByID) (*OutputVehicles, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVehiclesById not implemented")
}
func (*UnimplementedVehiclesServer) GetVehiclesList(ctx context.Context, req *VehiclesRequest) (*OutputVehicles, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVehiclesList not implemented")
}

func RegisterVehiclesServer(s *grpc.Server, srv VehiclesServer) {
	s.RegisterService(&_Vehicles_serviceDesc, srv)
}

func _Vehicles_CreateVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VehiclesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehiclesServer).CreateVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/packets.Vehicles/CreateVehicle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehiclesServer).CreateVehicle(ctx, req.(*VehiclesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vehicles_UpdateVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVehiclesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehiclesServer).UpdateVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/packets.Vehicles/UpdateVehicle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehiclesServer).UpdateVehicle(ctx, req.(*UpdateVehiclesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vehicles_GetVehiclesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VehiclesRequestByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehiclesServer).GetVehiclesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/packets.Vehicles/GetVehiclesById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehiclesServer).GetVehiclesById(ctx, req.(*VehiclesRequestByID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vehicles_DeleteVehiclesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VehiclesRequestByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehiclesServer).DeleteVehiclesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/packets.Vehicles/DeleteVehiclesById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehiclesServer).DeleteVehiclesById(ctx, req.(*VehiclesRequestByID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vehicles_GetVehiclesList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VehiclesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehiclesServer).GetVehiclesList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/packets.Vehicles/GetVehiclesList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehiclesServer).GetVehiclesList(ctx, req.(*VehiclesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Vehicles_serviceDesc = grpc.ServiceDesc{
	ServiceName: "packets.Vehicles",
	HandlerType: (*VehiclesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVehicle",
			Handler:    _Vehicles_CreateVehicle_Handler,
		},
		{
			MethodName: "UpdateVehicle",
			Handler:    _Vehicles_UpdateVehicle_Handler,
		},
		{
			MethodName: "GetVehiclesById",
			Handler:    _Vehicles_GetVehiclesById_Handler,
		},
		{
			MethodName: "DeleteVehiclesById",
			Handler:    _Vehicles_DeleteVehiclesById_Handler,
		},
		{
			MethodName: "GetVehiclesList",
			Handler:    _Vehicles_GetVehiclesList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocs/vehicles.proto",
}
